package io.github.newagewriter.processor.mapper

/**
 * Mapper factory interface that define the way of finding mapper for given object.
 * Implementation of this factory will be auto generated by processor.
 * Processor generate list of available mapper based on classes annotated with [io.github.newagewriter.mapper.Mapper]
 */
interface MapperFactory {

    /**
     * Method get mapper for given object
     * @return instance of mapper for given object or null if mapper for object doesn't exist
     */
    fun<T> of(obj: T): AbstractMapper<T>? where T : Any

    /**
     * Method get mapper for given class
     * @return instance of mapper for given class or null if mapper for this class doesn't exist
     */
    fun<T> forClass(obj: Class<T>, map: Map<String, Any?>): AbstractMapper<T>? where T : Any
}
